# Generated by Django 5.2.17 on 2026-10-03 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lost_reports', '0003_lostreport_collection_officer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('released', 'Released'), ('refused', 'Refused')], max_length=20)),
                ('proof_shown', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lost_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handover_attempts', to='lost_reports.lostreport')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handover_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('lost_report', 'attempt_number'), name='unique_handover_attempt_number')],
            },
        ),
    ]
