# Generated by Django 5.2.17 on 2026-09-21 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosteDePolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=80, unique=True)),
                ('nom', models.CharField(max_length=120)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=80)),
                ('telephone', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_proprietaire', models.CharField(max_length=150)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('numero_document', models.CharField(blank=True, max_length=50)),
                ('date_decouverte', models.DateField()),
                ('lieu_decouverte', models.CharField(max_length=200)),
                ('contact_declarant', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('depose', 'Déposé au poste'), ('recupere', 'Récupéré')], default='depose', max_length=10)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retrouves.postedepolice')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retrouves.typedocument')),
            ],
        ),
    ]
