# Generated by Django 5.2.17 on 2026-09-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrouves', '0003_document_agent_recuperation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='code_reference',
            field=models.CharField(default='', editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
