# Generated by Django 5.2.17 on 2026-10-03 00:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_seed_categories'),
        ('stations', '0002_seed_regions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('name_on_document', models.CharField(blank=True, max_length=200)),
                ('document_number', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('issuing_organisation', models.CharField(blank=True, max_length=200)),
                ('place_detail', models.CharField(blank=True, max_length=300)),
                ('date_found', models.DateField()),
                ('status', models.CharField(choices=[('awaiting_drop_off', 'Awaiting drop-off'), ('at_station', 'At the station'), ('owner_may_be_found', 'Owner may be found'), ('returned_to_owner', 'Returned to owner'), ('unclaimed', 'Unclaimed'), ('drop_off_declined', 'Drop-off declined')], default='awaiting_drop_off', max_length=30)),
                ('drop_off_code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='found_reports', to='documents.documentcategory')),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='found_reports', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='found_reports', to='stations.region')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='found_reports', to='stations.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
