# Generated by Django 5.2.17 on 2026-10-03 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found_reports', '0001_initial'),
        ('lost_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostreport',
            name='collection_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lostreport',
            name='matched_found_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matched_lost_reports', to='found_reports.foundreport'),
        ),
    ]
