# Generated by Django 5.2.17 on 2026-10-03 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_reports', '0002_lostreport_collection_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lostreport',
            name='collection_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections_handled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostreport',
            name='officer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lostreport',
            name='owner_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
